# Generated by Django 4.2.14 on 2024-07-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnomovil', '0002_celular_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
