# Generated by Django 4.2 on 2024-07-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnomovil', '0004_celular_marca_celular_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
