# Generated by Django 4.2 on 2024-07-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnomovil', '0005_alter_celular_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='celular',
            name='marca',
        ),
        migrations.AddField(
            model_name='celular',
            name='marca',
            field=models.ManyToManyField(to='tecnomovil.categoria'),
        ),
    ]
